/**
 * Unimoove API
 * An API for the Unimoove application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TripCreationRequest', 'model/ReservationPaginatedResponse', 'model/TripArrivalPlaceChangeRequest', 'model/TripDepartureDateTimeChangeRequest', 'model/TripDeparturePlaceChangeRequest', 'model/TripNumberAvailableSeatsChangeRequest', 'model/TripPaginatedResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/TripCreationRequest'), require('../model/ReservationPaginatedResponse'), require('../model/TripArrivalPlaceChangeRequest'), require('../model/TripDepartureDateTimeChangeRequest'), require('../model/TripDeparturePlaceChangeRequest'), require('../model/TripNumberAvailableSeatsChangeRequest'), require('../model/TripPaginatedResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.UnimooveApi) {
      root.UnimooveApi = {};
    }
    root.UnimooveApi.TripsApi = factory(root.UnimooveApi.ApiClient, root.UnimooveApi.TripCreationRequest, root.UnimooveApi.ReservationPaginatedResponse, root.UnimooveApi.TripArrivalPlaceChangeRequest, root.UnimooveApi.TripDepartureDateTimeChangeRequest, root.UnimooveApi.TripDeparturePlaceChangeRequest, root.UnimooveApi.TripNumberAvailableSeatsChangeRequest, root.UnimooveApi.TripPaginatedResponse);
  }
}(this, function(ApiClient, TripCreationRequest, ReservationPaginatedResponse, TripArrivalPlaceChangeRequest, TripDepartureDateTimeChangeRequest, TripDeparturePlaceChangeRequest, TripNumberAvailableSeatsChangeRequest, TripPaginatedResponse) {
  'use strict';

  /**
   * Trips service.
   * @module api/TripsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new TripsApi. 
   * @alias module:api/TripsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addTrip operation.
     * @callback module:api/TripsApi~addTripCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Adds a trip
     * Adds a new trip to the system
     * @param {Object} opts Optional parameters
     * @param {module:model/TripCreationRequest} opts.body Trip to add
     * @param {module:api/TripsApi~addTripCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addTrip = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['*_/_*'];
      var returnType = null;

      return this.apiClient.callApi(
        '/trips', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTrip operation.
     * @callback module:api/TripsApi~deleteTripCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a trip
     * @param {String} idTrip By passing in the appropriate trip ID, you can delete the trip.
     * @param {module:api/TripsApi~deleteTripCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteTrip = function(idTrip, callback) {
      var postBody = null;

      // verify the required parameter 'idTrip' is set
      if (idTrip == undefined || idTrip == null) {
        throw "Missing the required parameter 'idTrip' when calling deleteTrip";
      }


      var pathParams = {
        'idTrip': idTrip
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = [];
      var accepts = ['*_/_*'];
      var returnType = null;

      return this.apiClient.callApi(
        '/trips/{idTrip}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getTripReservations operation.
     * @callback module:api/TripsApi~getTripReservationsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ReservationPaginatedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets all the reservations for a trip
     * Gets all the reservations for a trip.
     * @param {String} idTrip idTrip
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.page the number of the page (default to 0)
     * @param {Integer} opts.size the number of element per page (default to 25)
     * @param {module:api/TripsApi~getTripReservationsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ReservationPaginatedResponse}
     */
    this.getTripReservations = function(idTrip, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'idTrip' is set
      if (idTrip == undefined || idTrip == null) {
        throw "Missing the required parameter 'idTrip' when calling getTripReservations";
      }


      var pathParams = {
        'idTrip': idTrip
      };
      var queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = ReservationPaginatedResponse;

      return this.apiClient.callApi(
        '/trips/{idTrip}/reservations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the modifyTripArrivalPlace operation.
     * @callback module:api/TripsApi~modifyTripArrivalPlaceCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies the trip&#39;s arrival Place
     * The trip ID for the trip you want to modify
     * @param {String} idTrip idTrip
     * @param {Object} opts Optional parameters
     * @param {module:model/TripArrivalPlaceChangeRequest} opts.body The trip&#39;s new arrival place
     * @param {module:api/TripsApi~modifyTripArrivalPlaceCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.modifyTripArrivalPlace = function(idTrip, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'idTrip' is set
      if (idTrip == undefined || idTrip == null) {
        throw "Missing the required parameter 'idTrip' when calling modifyTripArrivalPlace";
      }


      var pathParams = {
        'idTrip': idTrip
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['*_/_*'];
      var returnType = null;

      return this.apiClient.callApi(
        '/trips/{idTrip}/arrivalPlace', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the modifyTripDepartureDateTime operation.
     * @callback module:api/TripsApi~modifyTripDepartureDateTimeCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies the trip&#39;s departure date and time
     * The trip ID for the trip you want to modify
     * @param {String} idTrip idTrip
     * @param {Object} opts Optional parameters
     * @param {module:model/TripDepartureDateTimeChangeRequest} opts.body The trip&#39;s new departure date and time
     * @param {module:api/TripsApi~modifyTripDepartureDateTimeCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.modifyTripDepartureDateTime = function(idTrip, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'idTrip' is set
      if (idTrip == undefined || idTrip == null) {
        throw "Missing the required parameter 'idTrip' when calling modifyTripDepartureDateTime";
      }


      var pathParams = {
        'idTrip': idTrip
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['*_/_*'];
      var returnType = null;

      return this.apiClient.callApi(
        '/trips/{idTrip}/departureDateTime', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the modifyTripDeparturePlace operation.
     * @callback module:api/TripsApi~modifyTripDeparturePlaceCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies the trip&#39;s departurePlace
     * The trip ID for the trip you want to modify
     * @param {String} idTrip idTrip
     * @param {Object} opts Optional parameters
     * @param {module:model/TripDeparturePlaceChangeRequest} opts.body The trip&#39;s new departure place
     * @param {module:api/TripsApi~modifyTripDeparturePlaceCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.modifyTripDeparturePlace = function(idTrip, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'idTrip' is set
      if (idTrip == undefined || idTrip == null) {
        throw "Missing the required parameter 'idTrip' when calling modifyTripDeparturePlace";
      }


      var pathParams = {
        'idTrip': idTrip
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['*_/_*'];
      var returnType = null;

      return this.apiClient.callApi(
        '/trips/{idTrip}/departurePlace', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the modifyTripNumberAvailableSeats operation.
     * @callback module:api/TripsApi~modifyTripNumberAvailableSeatsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modifies the trip&#39;s number of available seats
     * The trip ID for the trip you want to modify
     * @param {String} idTrip idTrip
     * @param {Object} opts Optional parameters
     * @param {module:model/TripNumberAvailableSeatsChangeRequest} opts.body The trip&#39;s new number of available seats
     * @param {module:api/TripsApi~modifyTripNumberAvailableSeatsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.modifyTripNumberAvailableSeats = function(idTrip, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'idTrip' is set
      if (idTrip == undefined || idTrip == null) {
        throw "Missing the required parameter 'idTrip' when calling modifyTripNumberAvailableSeats";
      }


      var pathParams = {
        'idTrip': idTrip
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['*_/_*'];
      var returnType = null;

      return this.apiClient.callApi(
        '/trips/{idTrip}/numberAvailableSeats', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the obtainTrips operation.
     * @callback module:api/TripsApi~obtainTripsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TripPaginatedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtains the trips registered by the user
     * @param {String} username username
     * @param {Object} opts Optional parameters
     * @param {Integer} opts.page the number of the page (default to 0)
     * @param {Integer} opts.size the number of element per page (default to 25)
     * @param {module:api/TripsApi~obtainTripsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TripPaginatedResponse}
     */
    this.obtainTrips = function(username, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'username' is set
      if (username == undefined || username == null) {
        throw "Missing the required parameter 'username' when calling obtainTrips";
      }


      var pathParams = {
        'username': username
      };
      var queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = TripPaginatedResponse;

      return this.apiClient.callApi(
        '/users/{username}/trips', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the searchTrips operation.
     * @callback module:api/TripsApi~searchTripsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TripPaginatedResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Searches for trips
     * Searches for trips with the specified departure and arrival place and date.
     * @param {Object} opts Optional parameters
     * @param {String} opts.arrivalPlace the arrival place for the trip
     * @param {String} opts.departureDateTime the departure time for the trip
     * @param {String} opts.departurePlace the departure place for the trip
     * @param {Integer} opts.page the number of the page (default to 0)
     * @param {Integer} opts.size the number of element per page (default to 25)
     * @param {module:api/TripsApi~searchTripsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TripPaginatedResponse}
     */
    this.searchTrips = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'arrivalPlace': opts['arrivalPlace'],
        'departureDateTime': opts['departureDateTime'],
        'departurePlace': opts['departurePlace'],
        'page': opts['page'],
        'size': opts['size']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['ApiKeyAuth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = TripPaginatedResponse;

      return this.apiClient.callApi(
        '/trips', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
