/**
 * Unimoove API
 * An API for the Unimoove application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PaginationInfo', 'model/ReservationResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PaginationInfo'), require('./ReservationResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.UnimooveApi) {
      root.UnimooveApi = {};
    }
    root.UnimooveApi.ReservationPaginatedResponse = factory(root.UnimooveApi.ApiClient, root.UnimooveApi.PaginationInfo, root.UnimooveApi.ReservationResponse);
  }
}(this, function(ApiClient, PaginationInfo, ReservationResponse) {
  'use strict';




  /**
   * The ReservationPaginatedResponse model module.
   * @module model/ReservationPaginatedResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ReservationPaginatedResponse</code>.
   * @alias module:model/ReservationPaginatedResponse
   * @class
   * @param pages {Array.<module:model/ReservationResponse>} 
   * @param paginationInfo {module:model/PaginationInfo} 
   */
  var exports = function(pages, paginationInfo) {
    var _this = this;

    _this['pages'] = pages;
    _this['paginationInfo'] = paginationInfo;
  };

  /**
   * Constructs a <code>ReservationPaginatedResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReservationPaginatedResponse} obj Optional instance to populate.
   * @return {module:model/ReservationPaginatedResponse} The populated <code>ReservationPaginatedResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pages')) {
        obj['pages'] = ApiClient.convertToType(data['pages'], [ReservationResponse]);
      }
      if (data.hasOwnProperty('paginationInfo')) {
        obj['paginationInfo'] = PaginationInfo.constructFromObject(data['paginationInfo']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ReservationResponse>} pages
   */
  exports.prototype['pages'] = undefined;
  /**
   * @member {module:model/PaginationInfo} paginationInfo
   */
  exports.prototype['paginationInfo'] = undefined;



  return exports;
}));


