/**
 * Unimoove API
 * An API for the Unimoove application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TripReservationResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TripReservationResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.UnimooveApi) {
      root.UnimooveApi = {};
    }
    root.UnimooveApi.ReservationResponse = factory(root.UnimooveApi.ApiClient, root.UnimooveApi.TripReservationResponse);
  }
}(this, function(ApiClient, TripReservationResponse) {
  'use strict';




  /**
   * The ReservationResponse model module.
   * @module model/ReservationResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ReservationResponse</code>.
   * @alias module:model/ReservationResponse
   * @class
   * @param dateTimeReservation {Date} 
   * @param id {Integer} 
   * @param status {Integer} 
   * @param trip {module:model/TripReservationResponse} 
   */
  var exports = function(dateTimeReservation, id, status, trip) {
    var _this = this;

    _this['dateTimeReservation'] = dateTimeReservation;
    _this['id'] = id;
    _this['status'] = status;
    _this['trip'] = trip;
  };

  /**
   * Constructs a <code>ReservationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReservationResponse} obj Optional instance to populate.
   * @return {module:model/ReservationResponse} The populated <code>ReservationResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('dateTimeReservation')) {
        obj['dateTimeReservation'] = ApiClient.convertToType(data['dateTimeReservation'], 'Date');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'Integer');
      }
      if (data.hasOwnProperty('trip')) {
        obj['trip'] = TripReservationResponse.constructFromObject(data['trip']);
      }
    }
    return obj;
  }

  /**
   * @member {Date} dateTimeReservation
   */
  exports.prototype['dateTimeReservation'] = undefined;
  /**
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Integer} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {module:model/TripReservationResponse} trip
   */
  exports.prototype['trip'] = undefined;



  return exports;
}));


