/**
 * Unimoove API
 * An API for the Unimoove application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UnimooveApi);
  }
}(this, function(expect, UnimooveApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UnimooveApi.TripsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TripsApi', function() {
    describe('addTrip', function() {
      it('should call addTrip successfully', function(done) {
        //uncomment below and update the code to test addTrip
        //instance.addTrip(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTrip', function() {
      it('should call deleteTrip successfully', function(done) {
        //uncomment below and update the code to test deleteTrip
        //instance.deleteTrip(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTripReservations', function() {
      it('should call getTripReservations successfully', function(done) {
        //uncomment below and update the code to test getTripReservations
        //instance.getTripReservations(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('modifyTripArrivalPlace', function() {
      it('should call modifyTripArrivalPlace successfully', function(done) {
        //uncomment below and update the code to test modifyTripArrivalPlace
        //instance.modifyTripArrivalPlace(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('modifyTripDepartureDateTime', function() {
      it('should call modifyTripDepartureDateTime successfully', function(done) {
        //uncomment below and update the code to test modifyTripDepartureDateTime
        //instance.modifyTripDepartureDateTime(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('modifyTripDeparturePlace', function() {
      it('should call modifyTripDeparturePlace successfully', function(done) {
        //uncomment below and update the code to test modifyTripDeparturePlace
        //instance.modifyTripDeparturePlace(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('modifyTripNumberAvailableSeats', function() {
      it('should call modifyTripNumberAvailableSeats successfully', function(done) {
        //uncomment below and update the code to test modifyTripNumberAvailableSeats
        //instance.modifyTripNumberAvailableSeats(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('obtainTrips', function() {
      it('should call obtainTrips successfully', function(done) {
        //uncomment below and update the code to test obtainTrips
        //instance.obtainTrips(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchTrips', function() {
      it('should call searchTrips successfully', function(done) {
        //uncomment below and update the code to test searchTrips
        //instance.searchTrips(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
