/**
 * Unimoove API
 * An API for the Unimoove application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UnimooveApi);
  }
}(this, function(expect, UnimooveApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UnimooveApi.UsersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersApi', function() {
    describe('addUser', function() {
      it('should call addUser successfully', function(done) {
        //uncomment below and update the code to test addUser
        //instance.addUser(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUser', function() {
      it('should call deleteUser successfully', function(done) {
        //uncomment below and update the code to test deleteUser
        //instance.deleteUser(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUser', function() {
      it('should call getUser successfully', function(done) {
        //uncomment below and update the code to test getUser
        //instance.getUser(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('modifyUserBirthdate', function() {
      it('should call modifyUserBirthdate successfully', function(done) {
        //uncomment below and update the code to test modifyUserBirthdate
        //instance.modifyUserBirthdate(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('modifyUserEmail', function() {
      it('should call modifyUserEmail successfully', function(done) {
        //uncomment below and update the code to test modifyUserEmail
        //instance.modifyUserEmail(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('modifyUserGender', function() {
      it('should call modifyUserGender successfully', function(done) {
        //uncomment below and update the code to test modifyUserGender
        //instance.modifyUserGender(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('modifyUserLastname', function() {
      it('should call modifyUserLastname successfully', function(done) {
        //uncomment below and update the code to test modifyUserLastname
        //instance.modifyUserLastname(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('modifyUserName', function() {
      it('should call modifyUserName successfully', function(done) {
        //uncomment below and update the code to test modifyUserName
        //instance.modifyUserName(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('modifyUserPassword', function() {
      it('should call modifyUserPassword successfully', function(done) {
        //uncomment below and update the code to test modifyUserPassword
        //instance.modifyUserPassword(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('modifyUserRole', function() {
      it('should call modifyUserRole successfully', function(done) {
        //uncomment below and update the code to test modifyUserRole
        //instance.modifyUserRole(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('modifyUserUsername', function() {
      it('should call modifyUserUsername successfully', function(done) {
        //uncomment below and update the code to test modifyUserUsername
        //instance.modifyUserUsername(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchUser', function() {
      it('should call searchUser successfully', function(done) {
        //uncomment below and update the code to test searchUser
        //instance.searchUser(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
